<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

         // Empty the table
        $countries = Country::all();

        // if(sizeof($countries)==0){
        // Get all from the JSON file
        // $JSON_countries = Country::allJSON();

        // foreach ($JSON_countries as $country) {
        //     Country::firstOrCreate([
        //         'name'           => ((isset($country['name'])) ? $country['name'] : null),
        //         'dial_code'              => ((isset($country['dial_code'])) ? $country['dial_code'] : null),
        //         'code'   => ((isset($country['iso_3166_2'])) ? $country['iso_3166_2'] : null),
        //         'flag'   => ((isset($country['flag'])) ? $country['flag'] : null),
        //         'currency_name'   => ((isset($country['currency'])) ? $country['currency'] : null),
        //         'currency_code'   => ((isset($country['currency_code'])) ? $country['currency_code'] : null),
        //         'currency_symbol'   => ((isset($country['currency_symbol'])) ? $country['currency_symbol'] : null),
        //         'dial_min_length'   => ((isset($country['minLength'])) ? $country['minLength'] : null),
        //         'dial_max_length'   => ((isset($country['maxLength'])) ? $country['maxLength'] : null),
        //     ]);
        // }
        // }

        $countryData = [
            ['name' => 'Afghanistan', 'dial_code' => '+93', 'code' => 'AF', 'currency_name' => 'Afghan Afghani', 'currency_code' => 'AFN', 'currency_symbol' => '؋'],
            ['name' => 'Albania', 'dial_code' => '+355', 'code' => 'AL', 'currency_name' => 'Albanian Lek', 'currency_code' => 'ALL', 'currency_symbol' => 'L'],
            ['name' => 'Algeria', 'dial_code' => '+213', 'code' => 'DZ', 'currency_name' => 'Algerian Dinar', 'currency_code' => 'DZD', 'currency_symbol' => 'د.ج'],
            ['name' => 'Andorra', 'dial_code' => '+376', 'code' => 'AD', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Angola', 'dial_code' => '+244', 'code' => 'AO', 'currency_name' => 'Angolan Kwanza', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz'],
            ['name' => 'Antigua and Barbuda', 'dial_code' => '+1 268', 'code' => 'AG', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Argentina', 'dial_code' => '+54', 'code' => 'AR', 'currency_name' => 'Argentine Peso', 'currency_code' => 'ARS', 'currency_symbol' => '$'],
            ['name' => 'Armenia', 'dial_code' => '+374', 'code' => 'AM', 'currency_name' => 'Armenian Dram', 'currency_code' => 'AMD', 'currency_symbol' => '֏'],
            ['name' => 'Australia', 'dial_code' => '+61', 'code' => 'AU', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Austria', 'dial_code' => '+43', 'code' => 'AT', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Azerbaijan', 'dial_code' => '+994', 'code' => 'AZ', 'currency_name' => 'Azerbaijani Manat', 'currency_code' => 'AZN', 'currency_symbol' => '₼'],
            ['name' => 'Bahamas', 'dial_code' => '+1 242', 'code' => 'BS', 'currency_name' => 'Bahamian Dollar', 'currency_code' => 'BSD', 'currency_symbol' => '$'],
            ['name' => 'Bahrain', 'dial_code' => '+973', 'code' => 'BH', 'currency_name' => 'Bahraini Dinar', 'currency_code' => 'BHD', 'currency_symbol' => 'د.ب'],
            ['name' => 'Bangladesh', 'dial_code' => '+880', 'code' => 'BD', 'currency_name' => 'Bangladeshi Taka', 'currency_code' => 'BDT', 'currency_symbol' => '৳'],
            ['name' => 'Barbados', 'dial_code' => '+1 246', 'code' => 'BB', 'currency_name' => 'Barbadian Dollar', 'currency_code' => 'BBD', 'currency_symbol' => '$'],
            ['name' => 'Belarus', 'dial_code' => '+375', 'code' => 'BY', 'currency_name' => 'Belarusian Ruble', 'currency_code' => 'BYN', 'currency_symbol' => 'Br'],
            ['name' => 'Belgium', 'dial_code' => '+32', 'code' => 'BE', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Belize', 'dial_code' => '+501', 'code' => 'BZ', 'currency_name' => 'Belize Dollar', 'currency_code' => 'BZD', 'currency_symbol' => '$'],
            ['name' => 'Benin', 'dial_code' => '+229', 'code' => 'BJ', 'currency_name' => 'CFA Franc', 'currency_code' => 'XOF', 'currency_symbol' => '₣'],
            ['name' => 'Bhutan', 'dial_code' => '+975', 'code' => 'BT', 'currency_name' => 'Bhutanese Ngultrum', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu'],
            ['name' => 'Bolivia', 'dial_code' => '+591', 'code' => 'BO', 'currency_name' => 'Bolivian Boliviano', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs'],
            ['name' => 'Bosnia and Herzegovina', 'dial_code' => '+387', 'code' => 'BA', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark', 'currency_code' => 'BAM', 'currency_symbol' => 'KM'],
            ['name' => 'Botswana', 'dial_code' => '+267', 'code' => 'BW', 'currency_name' => 'Botswana Pula', 'currency_code' => 'BWP', 'currency_symbol' => 'P'],
            ['name' => 'Brazil', 'dial_code' => '+55', 'code' => 'BR', 'currency_name' => 'Brazilian Real', 'currency_code' => 'BRL', 'currency_symbol' => 'R$'],
            ['name' => 'Brunei', 'dial_code' => '+673', 'code' => 'BN', 'currency_name' => 'Brunei Dollar', 'currency_code' => 'BND', 'currency_symbol' => '$'],
            ['name' => 'Bulgaria', 'dial_code' => '+359', 'code' => 'BG', 'currency_name' => 'Bulgarian Lev', 'currency_code' => 'BGN', 'currency_symbol' => 'лв'],
            ['name' => 'Burkina Faso', 'dial_code' => '+226', 'code' => 'BF', 'currency_name' => 'CFA Franc', 'currency_code' => 'XOF', 'currency_symbol' => '₣'],
            ['name' => 'Burundi', 'dial_code' => '+257', 'code' => 'BI', 'currency_name' => 'Burundian Franc', 'currency_code' => 'BIF', 'currency_symbol' => 'BFr'],
            ['name' => 'Cabo Verde', 'dial_code' => '+238', 'code' => 'CV', 'currency_name' => 'Cape Verdean Escudo', 'currency_code' => 'CVE', 'currency_symbol' => 'Esc'],
            ['name' => 'Cambodia', 'dial_code' => '+855', 'code' => 'KH', 'currency_name' => 'Cambodian Riel', 'currency_code' => 'KHR', 'currency_symbol' => '៛'],
            ['name' => 'Cameroon', 'dial_code' => '+237', 'code' => 'CM', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'XAF', 'currency_symbol' => '₣'],
            ['name' => 'Canada', 'dial_code' => '+1', 'code' => 'CA', 'currency_name' => 'Canadian Dollar', 'currency_code' => 'CAD', 'currency_symbol' => '$'],
            ['name' => 'Central African Republic', 'dial_code' => '+236', 'code' => 'CF', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'XAF', 'currency_symbol' => '₣'],
            ['name' => 'Chad', 'dial_code' => '+235', 'code' => 'TD', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'XAF', 'currency_symbol' => '₣'],
            ['name' => 'Chile', 'dial_code' => '+56', 'code' => 'CL', 'currency_name' => 'Chilean Peso', 'currency_code' => 'CLP', 'currency_symbol' => '$'],
            ['name' => 'China', 'dial_code' => '+86', 'code' => 'CN', 'currency_name' => 'Renminbi', 'currency_code' => 'CNY', 'currency_symbol' => '¥'],
            ['name' => 'Colombia', 'dial_code' => '+57', 'code' => 'CO', 'currency_name' => 'Colombian Peso', 'currency_code' => 'COP', 'currency_symbol' => '$'],
            ['name' => 'Comoros', 'dial_code' => '+269', 'code' => 'KM', 'currency_name' => 'Comorian Franc', 'currency_code' => 'KMF', 'currency_symbol' => 'Fr'],
            ['name' => 'Congo (Congo-Brazzaville)', 'dial_code' => '+242', 'code' => 'CG', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Congo (Democratic Republic of the Congo)', 'dial_code' => '+243', 'code' => 'CD', 'currency_name' => 'Congolese Franc', 'currency_code' => 'CDF', 'currency_symbol' => '₣'],
            ['name' => 'Costa Rica', 'dial_code' => '+506', 'code' => 'CR', 'currency_name' => 'Costa Rican Colón', 'currency_code' => 'CRC', 'currency_symbol' => '₡'],
            ['name' => 'Croatia', 'dial_code' => '+385', 'code' => 'HR', 'currency_name' => 'Croatian Kuna', 'currency_code' => 'HRK', 'currency_symbol' => 'kn'],
            ['name' => 'Cuba', 'dial_code' => '+53', 'code' => 'CU', 'currency_name' => 'Cuban Peso', 'currency_code' => 'CUP', 'currency_symbol' => '$'],
            ['name' => 'Cyprus', 'dial_code' => '+357', 'code' => 'CY', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Czech Republic (Czechia)', 'dial_code' => '+420', 'code' => 'CZ', 'currency_name' => 'Czech Koruna', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč'],
            ['name' => 'Congo (Congo-Brazzaville)', 'dial_code' => '+242', 'code' => 'CG', 'currency_name' => 'CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Congo (Democratic Republic of the Congo)', 'dial_code' => '+243', 'code' => 'CD', 'currency_name' => 'Congolese Franc', 'currency_code' => 'CDF', 'currency_symbol' => 'Fr'],
            ['name' => 'Costa Rica', 'dial_code' => '+506', 'code' => 'CR', 'currency_name' => 'Costa Rican Colón', 'currency_code' => 'CRC', 'currency_symbol' => '₡'],
            ['name' => 'Croatia', 'dial_code' => '+385', 'code' => 'HR', 'currency_name' => 'Croatian Kuna', 'currency_code' => 'HRK', 'currency_symbol' => 'kn'],
            ['name' => 'Cuba', 'dial_code' => '+53', 'code' => 'CU', 'currency_name' => 'Cuban Peso', 'currency_code' => 'CUP', 'currency_symbol' => '$'],
            ['name' => 'Cyprus', 'dial_code' => '+357', 'code' => 'CY', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Czech Republic (Czechia)', 'dial_code' => '+420', 'code' => 'CZ', 'currency_name' => 'Czech Koruna', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč'],
            ['name' => 'Denmark', 'dial_code' => '+45', 'code' => 'DK', 'currency_name' => 'Danish Krone', 'currency_code' => 'DKK', 'currency_symbol' => 'kr'],
            ['name' => 'Djibouti', 'dial_code' => '+253', 'code' => 'DJ', 'currency_name' => 'Djiboutian Franc', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj'],
            ['name' => 'Dominica', 'dial_code' => '+1 767', 'code' => 'DM', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Dominican Republic', 'dial_code' => '+1 809', 'code' => 'DO', 'currency_name' => 'Dominican Peso', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$'],
            ['name' => 'East Timor (Timor-Leste)', 'dial_code' => '+670', 'code' => 'TL', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Ecuador', 'dial_code' => '+593', 'code' => 'EC', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Egypt', 'dial_code' => '+20', 'code' => 'EG', 'currency_name' => 'Egyptian Pound', 'currency_code' => 'EGP', 'currency_symbol' => 'ج.م'],
            ['name' => 'El Salvador', 'dial_code' => '+503', 'code' => 'SV', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Equatorial Guinea', 'dial_code' => '+240', 'code' => 'GQ', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'XAF', 'currency_symbol' => '₣'],
            ['name' => 'Eritrea', 'dial_code' => '+291', 'code' => 'ER', 'currency_name' => 'Eritrean Nakfa', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk'],
            ['name' => 'Estonia', 'dial_code' => '+372', 'code' => 'EE', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Eswatini (Swaziland)', 'dial_code' => '+268', 'code' => 'SZ', 'currency_name' => 'Swazi Lilangeni', 'currency_code' => 'SZL', 'currency_symbol' => 'E'],
            ['name' => 'Ethiopia', 'dial_code' => '+251', 'code' => 'ET', 'currency_name' => 'Ethiopian Birr', 'currency_code' => 'ETB', 'currency_symbol' => 'ብር'],
            ['name' => 'Fiji', 'dial_code' => '+679', 'code' => 'FJ', 'currency_name' => 'Fijian Dollar', 'currency_code' => 'FJD', 'currency_symbol' => '$'],
            ['name' => 'Finland', 'dial_code' => '+358', 'code' => 'FI', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'France', 'dial_code' => '+33', 'code' => 'FR', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Gabon', 'dial_code' => '+241', 'code' => 'GA', 'currency_name' => 'Central African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Gambia', 'dial_code' => '+220', 'code' => 'GM', 'currency_name' => 'Gambian Dalasi', 'currency_code' => 'GMD', 'currency_symbol' => 'D'],
            ['name' => 'Georgia', 'dial_code' => '+995', 'code' => 'GE', 'currency_name' => 'Georgian Lari', 'currency_code' => 'GEL', 'currency_symbol' => 'ლ'],
            ['name' => 'Germany', 'dial_code' => '+49', 'code' => 'DE', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Ghana', 'dial_code' => '+233', 'code' => 'GH', 'currency_name' => 'Ghanaian Cedi', 'currency_code' => 'GHS', 'currency_symbol' => '₵'],
            ['name' => 'Greece', 'dial_code' => '+30', 'code' => 'GR', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Grenada', 'dial_code' => '+1 473', 'code' => 'GD', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Guatemala', 'dial_code' => '+502', 'code' => 'GT', 'currency_name' => 'Guatemalan Quetzal', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q'],
            ['name' => 'Guinea', 'dial_code' => '+224', 'code' => 'GN', 'currency_name' => 'Guinean Franc', 'currency_code' => 'GNF', 'currency_symbol' => 'Fr'],
            ['name' => 'Guinea-Bissau', 'dial_code' => '+245', 'code' => 'GW', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Guyana', 'dial_code' => '+592', 'code' => 'GY', 'currency_name' => 'Guyanese Dollar', 'currency_code' => 'GYD', 'currency_symbol' => '$'],
            ['name' => 'Haiti', 'dial_code' => '+509', 'code' => 'HT', 'currency_name' => 'Gourde', 'currency_code' => 'HTG', 'currency_symbol' => 'G'],
            ['name' => 'Honduras', 'dial_code' => '+504', 'code' => 'HN', 'currency_name' => 'Honduran Lempira', 'currency_code' => 'HNL', 'currency_symbol' => 'L'],
            ['name' => 'Hungary', 'dial_code' => '+36', 'code' => 'HU', 'currency_name' => 'Hungarian Forint', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft'],
            ['name' => 'Iceland', 'dial_code' => '+354', 'code' => 'IS', 'currency_name' => 'Icelandic Króna', 'currency_code' => 'ISK', 'currency_symbol' => 'kr'],
            ['name' => 'India', 'dial_code' => '+91', 'code' => 'IN', 'currency_name' => 'Indian Rupee', 'currency_code' => 'INR', 'currency_symbol' => '₹'],
            ['name' => 'Indonesia', 'dial_code' => '+62', 'code' => 'ID', 'currency_name' => 'Indonesian Rupiah', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp'],
            ['name' => 'Iran', 'dial_code' => '+98', 'code' => 'IR', 'currency_name' => 'Iranian Rial', 'currency_code' => 'IRR', 'currency_symbol' => '﷼'],
            ['name' => 'Iraq', 'dial_code' => '+964', 'code' => 'IQ', 'currency_name' => 'Iraqi Dinar', 'currency_code' => 'IQD', 'currency_symbol' => 'د.ع'],
            ['name' => 'Ireland', 'dial_code' => '+353', 'code' => 'IE', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Israel', 'dial_code' => '+972', 'code' => 'IL', 'currency_name' => 'Israeli New Shekel', 'currency_code' => 'ILS', 'currency_symbol' => '₪'],
            ['name' => 'Italy', 'dial_code' => '+39', 'code' => 'IT', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Ivory Coast (Côte d\'Ivoire)', 'dial_code' => '+225', 'code' => 'CI', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Jamaica', 'dial_code' => '+1 876', 'code' => 'JM', 'currency_name' => 'Jamaican Dollar', 'currency_code' => 'JMD', 'currency_symbol' => '$'],
            ['name' => 'Japan', 'dial_code' => '+81', 'code' => 'JP', 'currency_name' => 'Japanese Yen', 'currency_code' => 'JPY', 'currency_symbol' => '¥'],
            ['name' => 'Jordan', 'dial_code' => '+962', 'code' => 'JO', 'currency_name' => 'Jordanian Dinar', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا'],
            ['name' => 'Kazakhstan', 'dial_code' => '+7', 'code' => 'KZ', 'currency_name' => 'Kazakhstani Tenge', 'currency_code' => 'KZT', 'currency_symbol' => '₸'],
            ['name' => 'Kenya', 'dial_code' => '+254', 'code' => 'KE', 'currency_name' => 'Kenyan Shilling', 'currency_code' => 'KES', 'currency_symbol' => 'KSh'],
            ['name' => 'Kiribati', 'dial_code' => '+686', 'code' => 'KI', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Korea (North)', 'dial_code' => '+850', 'code' => 'KP', 'currency_name' => 'North Korean Won', 'currency_code' => 'KPW', 'currency_symbol' => '₩'],
            ['name' => 'Korea (South)', 'dial_code' => '+82', 'code' => 'KR', 'currency_name' => 'South Korean Won', 'currency_code' => 'KRW', 'currency_symbol' => '₩'],
            ['name' => 'Kosovo', 'dial_code' => '+383', 'code' => 'XK', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Kuwait', 'dial_code' => '+965', 'code' => 'KW', 'currency_name' => 'Kuwaiti Dinar', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك'],
            ['name' => 'Kyrgyzstan', 'dial_code' => '+996', 'code' => 'KG', 'currency_name' => 'Kyrgyzstani Som', 'currency_code' => 'KGS', 'currency_symbol' => 'сом'],
            ['name' => 'Laos', 'dial_code' => '+856', 'code' => 'LA', 'currency_name' => 'Laotian Kip', 'currency_code' => 'LAK', 'currency_symbol' => '₭'],
            ['name' => 'Latvia', 'dial_code' => '+371', 'code' => 'LV', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Lebanon', 'dial_code' => '+961', 'code' => 'LB', 'currency_name' => 'Lebanese Pound', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل'],
            ['name' => 'Lesotho', 'dial_code' => '+266', 'code' => 'LS', 'currency_name' => 'Lesotho Loti', 'currency_code' => 'LSL', 'currency_symbol' => 'M'],
            ['name' => 'Liberia', 'dial_code' => '+231', 'code' => 'LR', 'currency_name' => 'Liberian Dollar', 'currency_code' => 'LRD', 'currency_symbol' => '$'],
            ['name' => 'Libya', 'dial_code' => '+218', 'code' => 'LY', 'currency_name' => 'Libyan Dinar', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د'],
            ['name' => 'Liechtenstein', 'dial_code' => '+423', 'code' => 'LI', 'currency_name' => 'Swiss Franc', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF'],
            ['name' => 'Lithuania', 'dial_code' => '+370', 'code' => 'LT', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Luxembourg', 'dial_code' => '+352', 'code' => 'LU', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Madagascar', 'dial_code' => '+261', 'code' => 'MG', 'currency_name' => 'Malagasy Ariary', 'currency_code' => 'MGA', 'currency_symbol' => 'MGA'],
            ['name' => 'Malawi', 'dial_code' => '+265', 'code' => 'MW', 'currency_name' => 'Malawian Kwacha', 'currency_code' => 'MWK', 'currency_symbol' => 'K'],
            ['name' => 'Malaysia', 'dial_code' => '+60', 'code' => 'MY', 'currency_name' => 'Malaysian Ringgit', 'currency_code' => 'MYR', 'currency_symbol' => 'RM'],
            ['name' => 'Maldives', 'dial_code' => '+960', 'code' => 'MV', 'currency_name' => 'Maldivian Rufiyaa', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf'],
            ['name' => 'Mali', 'dial_code' => '+223', 'code' => 'ML', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Malta', 'dial_code' => '+356', 'code' => 'MT', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Marshall Islands', 'dial_code' => '+692', 'code' => 'MH', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Mauritania', 'dial_code' => '+222', 'code' => 'MR', 'currency_name' => 'Ouguiya', 'currency_code' => 'MRO', 'currency_symbol' => 'UM'],
            ['name' => 'Mauritius', 'dial_code' => '+230', 'code' => 'MU', 'currency_name' => 'Mauritian Rupee', 'currency_code' => 'MUR', 'currency_symbol' => '₨'],
            ['name' => 'Mexico', 'dial_code' => '+52', 'code' => 'MX', 'currency_name' => 'Mexican Peso', 'currency_code' => 'MXN', 'currency_symbol' => '$'],
            ['name' => 'Micronesia', 'dial_code' => '+691', 'code' => 'FM', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Moldova', 'dial_code' => '+373', 'code' => 'MD', 'currency_name' => 'Moldovan Leu', 'currency_code' => 'MDL', 'currency_symbol' => 'lei'],
            ['name' => 'Monaco', 'dial_code' => '+377', 'code' => 'MC', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Mongolia', 'dial_code' => '+976', 'code' => 'MN', 'currency_name' => 'Mongolian Tögrög', 'currency_code' => 'MNT', 'currency_symbol' => '₮'],
            ['name' => 'Montenegro', 'dial_code' => '+382', 'code' => 'ME', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Morocco', 'dial_code' => '+212', 'code' => 'MA', 'currency_name' => 'Moroccan Dirham', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.'],
            ['name' => 'Mozambique', 'dial_code' => '+258', 'code' => 'MZ', 'currency_name' => 'Mozambican Metical', 'currency_code' => 'MZN', 'currency_symbol' => 'MT'],
            ['name' => 'Myanmar (Burma)', 'dial_code' => '+95', 'code' => 'MM', 'currency_name' => 'Burmese Kyat', 'currency_code' => 'MMK', 'currency_symbol' => 'Ks'],
            ['name' => 'Namibia', 'dial_code' => '+264', 'code' => 'NA', 'currency_name' => 'Namibian Dollar', 'currency_code' => 'NAD', 'currency_symbol' => '$'],
            ['name' => 'Nauru', 'dial_code' => '+674', 'code' => 'NR', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Nepal', 'dial_code' => '+977', 'code' => 'NP', 'currency_name' => 'Nepalese Rupee', 'currency_code' => 'NPR', 'currency_symbol' => '₨'],
            ['name' => 'Netherlands', 'dial_code' => '+31', 'code' => 'NL', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'New Zealand', 'dial_code' => '+64', 'code' => 'NZ', 'currency_name' => 'New Zealand Dollar', 'currency_code' => 'NZD', 'currency_symbol' => '$'],
            ['name' => 'Nicaragua', 'dial_code' => '+505', 'code' => 'NI', 'currency_name' => 'Nicaraguan Córdoba', 'currency_code' => 'NIO', 'currency_symbol' => 'C$'],
            ['name' => 'Niger', 'dial_code' => '+227', 'code' => 'NE', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Nigeria', 'dial_code' => '+234', 'code' => 'NG', 'currency_name' => 'Nigerian Naira', 'currency_code' => 'NGN', 'currency_symbol' => '₦'],
            ['name' => 'North Macedonia', 'dial_code' => '+389', 'code' => 'MK', 'currency_name' => 'Macedonian Denar', 'currency_code' => 'MKD', 'currency_symbol' => 'ден'],
            ['name' => 'Norway', 'dial_code' => '+47', 'code' => 'NO', 'currency_name' => 'Norwegian Krone', 'currency_code' => 'NOK', 'currency_symbol' => 'kr'],
            ['name' => 'Oman', 'dial_code' => '+968', 'code' => 'OM', 'currency_name' => 'Omani Rial', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع.'],
            ['name' => 'Pakistan', 'dial_code' => '+92', 'code' => 'PK', 'currency_name' => 'Pakistani Rupee', 'currency_code' => 'PKR', 'currency_symbol' => '₨'],
            ['name' => 'Palau', 'dial_code' => '+680', 'code' => 'PW', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Panama', 'dial_code' => '+507', 'code' => 'PA', 'currency_name' => 'Balboa', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.'],
            ['name' => 'Papua New Guinea', 'dial_code' => '+675', 'code' => 'PG', 'currency_name' => 'Kina', 'currency_code' => 'PGK', 'currency_symbol' => 'K'],
            ['name' => 'Paraguay', 'dial_code' => '+595', 'code' => 'PY', 'currency_name' => 'Paraguayan Guarani', 'currency_code' => 'PYG', 'currency_symbol' => '₲'],
            ['name' => 'Peru', 'dial_code' => '+51', 'code' => 'PE', 'currency_name' => 'Nuevo Sol', 'currency_code' => 'PEN', 'currency_symbol' => 'S/.'],
            ['name' => 'Philippines', 'dial_code' => '+63', 'code' => 'PH', 'currency_name' => 'Philippine Peso', 'currency_code' => 'PHP', 'currency_symbol' => '₱'],
            ['name' => 'Poland', 'dial_code' => '+48', 'code' => 'PL', 'currency_name' => 'Polish Zloty', 'currency_code' => 'PLN', 'currency_symbol' => 'zł'],
            ['name' => 'Portugal', 'dial_code' => '+351', 'code' => 'PT', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Qatar', 'dial_code' => '+974', 'code' => 'QA', 'currency_name' => 'Qatari Rial', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق'],
            ['name' => 'Romania', 'dial_code' => '+40', 'code' => 'RO', 'currency_name' => 'Romanian Leu', 'currency_code' => 'RON', 'currency_symbol' => 'lei'],
            ['name' => 'Russia', 'dial_code' => '+7', 'code' => 'RU', 'currency_name' => 'Russian Ruble', 'currency_code' => 'RUB', 'currency_symbol' => '₽'],
            ['name' => 'Rwanda', 'dial_code' => '+250', 'code' => 'RW', 'currency_name' => 'Rwandan Franc', 'currency_code' => 'RWF', 'currency_symbol' => 'Fr'],
            ['name' => 'Saint Kitts and Nevis', 'dial_code' => '+1 869', 'code' => 'KN', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Saint Lucia', 'dial_code' => '+1 758', 'code' => 'LC', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Saint Vincent and the Grenadines', 'dial_code' => '+1 784', 'code' => 'VC', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Samoa', 'dial_code' => '+685', 'code' => 'WS', 'currency_name' => 'Tala', 'currency_code' => 'WST', 'currency_symbol' => 'T'],
            ['name' => 'San Marino', 'dial_code' => '+378', 'code' => 'SM', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'São Tomé and Príncipe', 'dial_code' => '+239', 'code' => 'ST', 'currency_name' => 'São Tomé and Príncipe Dobra', 'currency_code' => 'STN', 'currency_symbol' => 'Db'],
            ['name' => 'Saudi Arabia', 'dial_code' => '+966', 'code' => 'SA', 'currency_name' => 'Saudi Riyal', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س'],
            ['name' => 'Senegal', 'dial_code' => '+221', 'code' => 'SN', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Serbia', 'dial_code' => '+381', 'code' => 'RS', 'currency_name' => 'Serbian Dinar', 'currency_code' => 'RSD', 'currency_symbol' => 'дин'],
            ['name' => 'Seychelles', 'dial_code' => '+248', 'code' => 'SC', 'currency_name' => 'Seychellois Rupee', 'currency_code' => 'SCR', 'currency_symbol' => '₨'],
            ['name' => 'Sierra Leone', 'dial_code' => '+232', 'code' => 'SL', 'currency_name' => 'Sierra Leonean Leone', 'currency_code' => 'SLL', 'currency_symbol' => 'Le'],
            ['name' => 'Singapore', 'dial_code' => '+65', 'code' => 'SG', 'currency_name' => 'Singapore Dollar', 'currency_code' => 'SGD', 'currency_symbol' => '$'],
            ['name' => 'Slovakia', 'dial_code' => '+421', 'code' => 'SK', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Slovenia', 'dial_code' => '+386', 'code' => 'SI', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Solomon Islands', 'dial_code' => '+677', 'code' => 'SB', 'currency_name' => 'Solomon Islands Dollar', 'currency_code' => 'SBD', 'currency_symbol' => '$'],
            ['name' => 'Somalia', 'dial_code' => '+252', 'code' => 'SO', 'currency_name' => 'Somali Shilling', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh'],
            ['name' => 'South Africa', 'dial_code' => '+27', 'code' => 'ZA', 'currency_name' => 'South African Rand', 'currency_code' => 'ZAR', 'currency_symbol' => 'R'],
            ['name' => 'South Sudan', 'dial_code' => '+211', 'code' => 'SS', 'currency_name' => 'South Sudanese Pound', 'currency_code' => 'SSP', 'currency_symbol' => '£'],
            ['name' => 'Spain', 'dial_code' => '+34', 'code' => 'ES', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Sri Lanka', 'dial_code' => '+94', 'code' => 'LK', 'currency_name' => 'Sri Lankan Rupee', 'currency_code' => 'LKR', 'currency_symbol' => 'Rs'],
            ['name' => 'Sudan', 'dial_code' => '+249', 'code' => 'SD', 'currency_name' => 'Sudanese Pound', 'currency_code' => 'SDG', 'currency_symbol' => 'ج.س'],
            ['name' => 'Suriname', 'dial_code' => '+597', 'code' => 'SR', 'currency_name' => 'Surinamese Dollar', 'currency_code' => 'SRD', 'currency_symbol' => '$'],
            ['name' => 'Sweden', 'dial_code' => '+46', 'code' => 'SE', 'currency_name' => 'Swedish Krona', 'currency_code' => 'SEK', 'currency_symbol' => 'kr'],
            ['name' => 'Switzerland', 'dial_code' => '+41', 'code' => 'CH', 'currency_name' => 'Swiss Franc', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF'],
            ['name' => 'Syria', 'dial_code' => '+963', 'code' => 'SY', 'currency_name' => 'Syrian Pound', 'currency_code' => 'SYP', 'currency_symbol' => '£'],
            ['name' => 'Taiwan', 'dial_code' => '+886', 'code' => 'TW', 'currency_name' => 'New Taiwan Dollar', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$'],
            ['name' => 'Tajikistan', 'dial_code' => '+992', 'code' => 'TJ', 'currency_name' => 'Tajikistani Somoni', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ'],
            ['name' => 'Tanzania', 'dial_code' => '+255', 'code' => 'TZ', 'currency_name' => 'Tanzanian Shilling', 'currency_code' => 'TZS', 'currency_symbol' => 'Sh'],
            ['name' => 'Thailand', 'dial_code' => '+66', 'code' => 'TH', 'currency_name' => 'Baht', 'currency_code' => 'THB', 'currency_symbol' => '฿'],
            ['name' => 'Togo', 'dial_code' => '+228', 'code' => 'TG', 'currency_name' => 'West African CFA Franc', 'currency_code' => 'CFA', 'currency_symbol' => '₣'],
            ['name' => 'Tonga', 'dial_code' => '+676', 'code' => 'TO', 'currency_name' => 'Paʻanga', 'currency_code' => 'TOP', 'currency_symbol' => 'T$'],
            ['name' => 'Trinidad and Tobago', 'dial_code' => '+1 868', 'code' => 'TT', 'currency_name' => 'Trinidad and Tobago Dollar', 'currency_code' => 'TTD', 'currency_symbol' => '$'],
            ['name' => 'Tunisia', 'dial_code' => '+216', 'code' => 'TN', 'currency_name' => 'Tunisian Dinar', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت'],
            ['name' => 'Turkey', 'dial_code' => '+90', 'code' => 'TR', 'currency_name' => 'Turkish Lira', 'currency_code' => 'TRY', 'currency_symbol' => '₺'],
            ['name' => 'Turkmenistan', 'dial_code' => '+993', 'code' => 'TM', 'currency_name' => 'Turkmenistan Manat', 'currency_code' => 'TMT', 'currency_symbol' => 'm'],
            ['name' => 'Tuvalu', 'dial_code' => '+688', 'code' => 'TV', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Uganda', 'dial_code' => '+256', 'code' => 'UG', 'currency_name' => 'Ugandan Shilling', 'currency_code' => 'UGX', 'currency_symbol' => 'Sh'],
            ['name' => 'Ukraine', 'dial_code' => '+380', 'code' => 'UA', 'currency_name' => 'Hryvnia', 'currency_code' => 'UAH', 'currency_symbol' => '₴'],
            ['name' => 'United Arab Emirates', 'dial_code' => '+971', 'code' => 'AE', 'currency_name' => 'UAE Dirham', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ'],
            ['name' => 'United Kingdom', 'dial_code' => '+44', 'code' => 'GB', 'currency_name' => 'Pound Sterling', 'currency_code' => 'GBP', 'currency_symbol' => '£'],
            ['name' => 'United States of America', 'dial_code' => '+1', 'code' => 'US', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Uruguay', 'dial_code' => '+598', 'code' => 'UY', 'currency_name' => 'Uruguayan Peso', 'currency_code' => 'UYU', 'currency_symbol' => '$'],
            ['name' => 'Uzbekistan', 'dial_code' => '+998', 'code' => 'UZ', 'currency_name' => 'Uzbekistani Som', 'currency_code' => 'UZS', 'currency_symbol' => 'сўм'],
            ['name' => 'Vanuatu', 'dial_code' => '+678', 'code' => 'VU', 'currency_name' => 'Vanuatu Vatu', 'currency_code' => 'VUV', 'currency_symbol' => 'Vt'],
            ['name' => 'Vatican City (Holy See)', 'dial_code' => '+39 06', 'code' => 'VA', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Venezuela', 'dial_code' => '+58', 'code' => 'VE', 'currency_name' => 'Venezuelan Bolívar', 'currency_code' => 'VES', 'currency_symbol' => 'Bs'],
            ['name' => 'Vietnam', 'dial_code' => '+84', 'code' => 'VN', 'currency_name' => 'Vietnamese Dong', 'currency_code' => 'VND', 'currency_symbol' => '₫'],
            ['name' => 'Yemen', 'dial_code' => '+967', 'code' => 'YE', 'currency_name' => 'Yemeni Rial', 'currency_code' => 'YER', 'currency_symbol' => '﷼'],
            ['name' => 'Zambia', 'dial_code' => '+260', 'code' => 'ZM', 'currency_name' => 'Zambian Kwacha', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK'],
            ['name' => 'Zimbabwe', 'dial_code' => '+263', 'code' => 'ZW', 'currency_name' => 'Zimbabwean Dollar', 'currency_code' => 'ZWD', 'currency_symbol' => '$'],
            // Add more countries as per the above pattern...
        ];

        foreach ($countryData as $country) {
            Country::firstOrCreate([
                'name' => $country['name'],
                'dial_code' => $country['dial_code'],
                'code' => $country['code'],
                'currency_name' => $country['currency_name'],
                'currency_code' => $country['currency_code'],
                'currency_symbol' => $country['currency_symbol'],
            ]);
        }

    }
}
